eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka,http://localhost1:8083/eureka
  instance:
      prefer-ip-address: true
